name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  node-version: "18"
  path: "KoLmafia"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
      - name: Install modules
        run: yarn install --immutable
      - name: Run ESLint & Prettier
        run: yarn run lint

  testBuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
      - name: Install modules
        run: yarn install --immutable
      - name: Build
        run: yarn run build

  push:
    runs-on: ubuntu-latest
    needs: [lint, testBuild]
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
      - name: Install modules
        run: yarn install --immutable
      - name: Build
        run: yarn run build

      - name: Push to Release
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: release
          FOLDER: ${{ env.path }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"
          SKIP_EMPTY_COMMITS: true
